version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
      -
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - aws s3 rm --recursive "s3://${ARTIFACTS_BUCKET}/"
      - aws cloudfront create-invalidation --distribution-id "${ARTIFACTS_CF_DISTRIBUTION}" --paths "/"

artifacts:
  files:
    - "**/*"
  base-directory: out
  discard-paths: no
